import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Users } from './Users';

@Injectable({
  providedIn: 'root'
})
export class RestService {

  constructor(private http : HttpClient) { }

  url : string  = "https://retoolapi.dev/gHVAWE/data"; //generated by https://retool.com/api-generator/, can use a localy place database;

  getUsers()
  {
    return this.http.get<Users[]>(this.url);
  }
  

}
